name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Activate virtual env
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Locally
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
      - name: Run Cargo Test
        run: cargo test
      - name: Run pytest
        run: |
          python -m pip install pytest
          python -m pytest tests/*
